name: quran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  arabic_numbers: 1.0.0
  audioplayers: 3.0.1
  flutter_native_splash: 2.2.16
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Hafs
      fonts: 
        - asset: assets/fonts/Hafs.ttf
  uses-material-design: true

flutter_icons: 
  android: launcher_icon
  image_path: assets/icons/quran.png
  image_path_android: assets/icons/quran-circle.png
  web: 
    image_path: assets/icons/quran.png
    background_color: '#FF5722'
    theme_color: '#FF5722'
    generate: true
  windows: 
    image_path: assets/icons/quran.png
    generate: true
    icon_size: 48
  macos: 
    image_path: assets/icons/quran.png
    generate: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#FF5722"
  #background_image: "assets/background.png"
  image: assets/icons/quran.png

assets: 
  - assets/fonts/

